version: '3.3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: orm_postgres
    environment:
      POSTGRES_PASSWORD: 'orm_password'
      POSTGRES_USER: 'orm_user'
      POSTGRES_DB: 'orm'
    ports:
      - '5432:5432'
    volumes:
      - "./db/script.sql:/docker-entrypoint-initdb.d/1.sql"
